### PR TITLE
Moved back to 2.0.5b, pull archived mods from modrinth

### PR DESCRIPTION
**Pull request by unrealJune**
Use modrinth to get missing mods.

I haven't done a lot of testing, but this seems to work.

### CODE REVIEW

**Comment by unrealJune** [comment]
I saw that the docker container can't be updated because of the archived mods, so I pulled them from modrinth where they're still hosted.

**Comment by claraphyll** [comment]
First off, thank you for working on this. At least Hephaestus seems to have a 1.18.2 version up on Modrinth.

However, for Vinery I get:
```
[...]
[18:34:57] [main/ERROR]: Incompatible mod set!
net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
         - Replace mod 'Vinery' (vinery) 1.1.4 with version 1.1.4 that is compatible with:
                 - minecraft 1.18.2
Unmet dependency listing:
         - Mod 'Vinery' (vinery) 1.1.4 requires any version between 1.19.2 (inclusive) and 1.20- (exclusive) of 'Minecraft' (minecraft), but only the wrong version is present: 1.18.2!
        at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51) ~[fabric-loader-0.14.22.jar:?]
        at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:192) ~[fabric-loader-0.14.22.jar:?]
        at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148) ~[fabric-loader-0.14.22.jar:?]
        at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68) [fabric-loader-0.14.22.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.14.22.jar:?]
        at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) [fabric-loader-0.14.22.jar:?]
        at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69) [server.jar:0.11.2]
```
It seems to me like there's no version of Vinery for 1.18.2 available on Modrinth (downloading the modpack in a launcher downloads Vinery 1.1.1 but the oldest version on Modrinth is 1.1.4), so it seems like the only way to get that version of the mod is to download it with a CurseForge client that has an API key

**Comment by unrealJune** [comment]
I did find this on modrinth, seems to be a fork of Vinery!

https://modrinth.com/mod/astral-vinery.

Might be worth taking a look!

**Comment by Erdragh** [comment]
(Author of the linked mod here)
Astral Vinery is an addon for Vinery I made specifically for the Create Astral modpack. It’s already in the server pack and it depends on the Vinery 1.18.2 1.1.4 version.

**Comment by Erdragh** [comment]
The dependency on vinery is stated here: https://github.com/Erdragh/Astral-Vinery/blob/develop/src/main/resources/fabric.mod.json

**Comment by Erdragh** [comment]
What could _theoretically_ work is the following:
- clone the astral vinery repo
- run gradle once, it should download the archived jar via the cursemaven
- extract said jar from the gradle cache

This feels rather dirty tho. Maybe a well formulated `curl` could access the maven too?

This all depends on cursemaven still serving the file, which I'm not certain about.

**Comment by unrealJune** [comment]
Hm, we could also pull a copy from the old modpack version? Just extract the last version's zip, and then copy over the vinery jar?

**Comment by Erdragh** [comment]
I don't see why not, it would mean downloading two separate server packs tho, which are rather large. Seeing as it only happens during the container build and not when using the container however, it shouldn't be an issue.

**Comment by unrealJune** [comment]
I think that's the play! It should be just as stable.

**Comment by unrealJune** [comment]
I just made the aforementioned changes!

**Comment by claraphyll** [comment]
Works on my machine. LGTM

**Pull request merged**
